baseURL = 'https://trashwbin.top/'
languageCode = 'zh-cn'
title = 'Trashwbin'
theme = 'introduction'
DefaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true  # 为所有语言创建子目录

# 添加 Markdown 渲染配置
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # 允许 HTML
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    style = "monokai"

[params]
    themeStyle = "light"
    favicon = "../icons/favicon.ico"
    showRSSButton = false
    fadeIn = true
    fadeInIndex = false
    
    # 添加导航设置
    showMenu = true
    showServices = true
    showProjects = true
    showBlog = true
    showContact = true
    showAbout = true
    
    # 个人信息
    firstName = "Abin"
    lastName = ""
    
    # 社交媒体链接
    [[params.social]]
        url = "https://gitee.com/trashwbin"
        icon = "fab fa-git-alt"
        
    [[params.social]]
        url = "mailto:Trashwbin@gmail.com"
        icon = "fas fa-envelope"
    [[params.social]]
        url = "https://github.com/Trashwbin"
        icon = "fab fa-github"

    DefaultContentLanguage = "zh"  # 添加这个参数用于模板中的判断

[languages]
    [languages.zh]
        languageName = "中文"
        contentDir = "content/zh"
        weight = 1
        title = "Trashwbin"

        [languages.zh.params]
            description = "后端开发 | AI驱动编程 | 算法"
            tagLine = "后端开发 | AI驱动编程 | 算法"
            footerText = "用 ❤️ 制作"

    [languages.en]
        languageName = "English"
        contentDir = "content/en"
        weight = 2
        title = "Trashwbin"

        [languages.en.params]
            description = "Backend Dev | AI-Driven Programming | Algorithms"
            tagLine = "Backend Dev | AI-Driven Programming | Algorithms"
            footerText = "Made with ❤️"
